### ISSUE TITLE
Lithuanian Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/lt.reactjs.org#1]
## Maintainer List

* @rokasmuningis
* @martynaskadisa
* @marturas 

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [ ] Home Page (@RokasMuningis)
* [ ] Tutorial (@MAstrauskas)

### Basics

* [x] Hello World (@marturas) 
* [ ] Introducing JSX (@marturas)
* [ ] Rendering Elements
* [ ] Components and Props
* [ ] State and Lifecycle
* [ ] Handling Events
* [ ] Conditional Rendering
* [ ] Lists and Keys
* [ ] Forms
* [ ] Lifting State Up
* [ ] Composition vs Inheritance
* [ ] Thinking in React

### API Reference

* [ ] React
* [ ] React.Component
* [ ] ReactDOM
* [ ] ReactDOMServer
* [ ] DOM Elements
* [ ] SyntheticEvent
* [ ] Test Utilities
* [ ] Shallow Renderer
* [ ] Test Renderer
* [ ] JS Environment Requirements
* [ ] Glossary

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [ ] tutorial/nav.yml
* [ ] docs/nav.yml

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started
* [ ] Add React to a Website
* [ ] Create a New React App
* [ ] CDN Links

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [ ] Introducing Hooks
  * [ ] Hooks at a Glance
  * [ ] Using the State Hook
  * [ ] Using the Effect Hook
  * [ ] Rules of Hooks
  * [ ] Building Your Own Hooks
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by tesseralis** [comment]
@RokasMuningis @martynaskadisa, please use this issue to track your progress!

**Comment by tesseralis** [comment]
@RokasMuningis how is the translation of the home page going?

**Comment by tesseralis** [comment]
Hi @RokasMuningis, just wanted to check in again on how your translations are doing.

@martynaskadisa, could you pick another page to help out on?

**Comment by RokasMuningis** [comment]
@tesseralis - had couple past weeks bit busy, but were planning to jump onto it this weekend. Hopefully homepage should be done. Sorry for the delay!

**Comment by tesseralis** [comment]
Okay! Thanks for letting me know!

**Comment by tesseralis** [comment]
Also, I wrote [a tweet] to spread the word. If you know of any Lithuanian React communities, you can also see if anyone wants to help out!

**Comment by martynaskadisa** [comment]
@tesseralis Sure thing, I just couldn't find time to work on this, so I didn't tick any of these boxes. I'll try to find some time for this project 😅

**Comment by keptup** [comment]
Hey.
I'd like to translate the "Hello World" page.
Sorry for a possibly lame question but I cloned the [repo](https://github.com/reactjs/lt.reactjs.org/) to my machine and no .git file is present (maybe it doesn't have to be there). How should I start tracking changes? What GitHub link should I use to be able to branch off of it?

**Comment by MAstrauskas** [comment]
Hi, I'd like to contribute and start working on **Tutorial** page. Let me know what you think.

**Comment by marturas** [comment]
> Hi, I'd like to contribute and start working on **Tutorial** page. Let me know what you think.

Hi, great! Just put your name next to it and reserve it, so no one will start working on it at the same time.

**Comment by MAstrauskas** [comment]
> > Hi, I'd like to contribute and start working on **Tutorial** page. Let me know what you think.
> 
> Hi, great! Just put your name next to it and reserve it, so no one will start working on it at the same time.

Would you be able to edit it as I believe only maintainers have access to update the issue? Thanks.

**Comment by ar1ja** [comment]
Hey, im lithuanian, seemingly this isnt moving anywhere since 2020, im more than happy to translate the home page at least, where do i start ? i mean *can* i even start

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
